<div class="row">
    <div class="col-md-6 col-lg-offset-3">
        <div class="widget wgreen">

            <div class="widget-head">
                <div class="pull-left">添加客户</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <!-- Form starts.  -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">姓名</label>
                            <div class="col-lg-8">
                                <input type="text" data-bind="value:name" class="form-control" placeholder="输入客户姓名">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label">是否为VIP</label>
                            <div class="col-lg-8">
                                <label class="checkbox-inline">
                                    <input type="checkbox" data-bind="checked:isVip" id="inlineCheckbox1" value="true">
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">手机号码</label>
                            <div class="col-lg-8">
                                <input type="text" data-bind="value:phoneNumber" class="form-control" placeholder="输入客户的手机号码">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">微信号</label>
                            <div class="col-lg-8">
                                <input type="text" data-bind="value:wechat" class="form-control" placeholder="输入客户的微信号">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">QQ</label>
                            <div class="col-lg-8">
                               <input type="text" data-bind="value:qq" class="form-control" placeholder="输入客户的QQ">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">备注</label>
                            <div class="col-lg-8">
                                <textarea class="form-control" rows="3" data-bind="value:remark" placeholder="输入备注信息"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-8 col-lg-offset-4">
                                <button type="submit" data-bind="click:submit" data-loading-text="正在验证数据.." class="btn btn-success submitTo">添加客户</button>
                                <button type="submit" data-bind="click:submitAndContinue" data-loading-text="正在验证数据.." class="btn btn-success submitTo">保存并继续添加</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="widget-foot">
                <!-- Footer goes here -->
            </div>
        </div>  

    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/customer/create-customer']);});");
?>
