<div class="row">
    <div class="col-md-6 col-lg-offset-3">
        <div class="widget wgreen">

            <div class="widget-head">
                <div class="pull-left">会员卡充值</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <h2 class="te-ce" style="padding: 13px 15px">
                    <span>余额: <span class="text-success">25</span> ￥</span> ,
                    <span>充值金额: <span class="text-danger">100</span> ￥</span>
                </h2>
                <hr/>
                <div class="padd">
                    <!-- Form starts.-->
                    <?php echo $this->form()->openTag($form);?>
                        <?php echo $this->bootstrapFormConllection($form);?>
                    <?php echo $this->form()->closeTag();?>
                </div>
            </div>
            <div class="widget-foot">
                <!-- Footer goes here -->
            </div>
        </div>

    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/customer/recharge']);});");
?>
