<div class='row'>
    <div class="col-md-12">
        <div class="pull-right">
            <button type="submit" class="btn btn-success">结账</button>
            <button type="reset" class="btn btn-default">重置表单</button>
        </div>
    </div>
</div>
<div class="row">

    <div class="col-md-6">
        <div class="widget wgreen">

            <div class="widget-head">
                <div class="pull-left">添加账单产品</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <!-- Form starts.  -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">款号</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="输入产品的唯一编号">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">数量</label>
                            <div class="col-lg-8">
                                <input type="text" class="form-control" placeholder="输入售出数量">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">售价</label>
                            <div class="col-lg-8">
                               <input type="text" class="form-control" placeholder="输入实际成交价格">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">手机号</label>
                            <div class="col-lg-8">
                               <input type="text" class="form-control" placeholder="输入会员的手机号码,非会员留空">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label visible-lg">备注</label>
                            <div class="col-lg-8">
                                <textarea class="form-control" rows="3" placeholder="输入备注信息"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-offset-4 col-lg-12">
                                <button type="submit" class="btn btn-success">添加此产品到账单</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="widget-foot">
                <!-- Footer goes here -->
            </div>
        </div>  

    </div>
    <div class="col-md-6">
        <div class="widget">

            <div class="widget-head">
                <div class="pull-left">此账单包括产品:</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>  
                <div class="clearfix"></div>
            </div>

            <div class="widget-content">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>款号</th>
                            <th>售价</th>
                            <th>数量</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>#9878</td>
                            <td>67</td>
                            <td>10</td>
                            <td>
                                <button class="btn btn-xs btn-success"><i class="icon-ok"></i> </button>
                                <button class="btn btn-xs btn-warning"><i class="icon-pencil"></i> </button>
                                <button class="btn btn-xs btn-danger"><i class="icon-remove"></i> </button>

                            </td>
                        </tr>                                                       
                        <tr>
                            <td>#9878</td>
                            <td>67</td>
                            <td>10</td>
                            <td>
                                <button class="btn btn-xs btn-success"><i class="icon-ok"></i> </button>
                                <button class="btn btn-xs btn-warning"><i class="icon-pencil"></i> </button>
                                <button class="btn btn-xs btn-danger"><i class="icon-remove"></i> </button>

                            </td>
                        </tr> 
                        <tr>
                            <td>#9878</td>
                            <td>67</td>
                            <td>10</td>
                            <td>
                                <button class="btn btn-xs btn-success"><i class="icon-ok"></i> </button>
                                <button class="btn btn-xs btn-warning"><i class="icon-pencil"></i> </button>
                                <button class="btn btn-xs btn-danger"><i class="icon-remove"></i> </button>

                            </td>
                        </tr> 
                        <tr>
                            <td>#9878</td>
                            <td>67</td>
                            <td>10</td>
                            <td>
                                <button class="btn btn-xs btn-success"><i class="icon-ok"></i> </button>
                                <button class="btn btn-xs btn-warning"><i class="icon-pencil"></i> </button>
                                <button class="btn btn-xs btn-danger"><i class="icon-remove"></i> </button>

                            </td>
                        </tr>
                        <tfoot>
                            <tr>
                                <td colspan="4"><div class="pull-right"><h3>总计:243￥&nbsp;</h3></div></td>
                            </tr>
                        </tfoot>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>
