<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <!-- Widget starts -->
        <div class="widget wred">
            <div class="widget-head">
                <i class="icon-lock"></i> 修改密码
            </div>
            <div class="widget-content">
                <div class="padd">

                    <form class="form-horizontal">
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="password">原密码</label>
                            <div class="col-lg-9">
                                <input type="password" data-bind="value:password" class="form-control" id="password" placeholder="请输入密码6-15字符">
                            </div>
                        </div>
                        <!-- Password -->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="newPassword">新密码</label>
                            <div class="col-lg-9">
                                <input type="password" data-bind="value:newPassword" class="form-control" id="newPassword" placeholder="请输入密码6-15字符">
                            </div>
                        </div>
                        <!-- RePassword -->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="confirm">重复密码</label>
                            <div class="col-lg-9">
                                <input type="password" data-bind="value:confirm" class="form-control" id="confirm" placeholder="请再次输入密码">
                            </div>
                        </div>
                        <!-- Accept box and button s-->
                        <div class="form-group">
                                <label class="control-label col-lg-3 visible-lg" for="">&nbsp;</label>
                                <div class="col-lg-9">
                                    <button type="submit" data-bind="click:submitAndContinue" data-loading-text="正在验证数据.." class="btn btn-danger submitTo">保存</button>
                                    <a class="btn btn-success submitTo" href="<?php echo $this->url('account',array('action'=>'edit-account'));?>">返回</a>
                                </div>
                            </div>
                    </form>

                </div>
            </div>
            <div class="widget-foot">
            </div>
        </div>
    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/account/change-password']);});");
?>