<div class="row">
    <div class="col-lg-6  col-lg-offset-3">
        <!-- Widget starts -->
        <div class="widget wred">
            <div class="widget-head">
                <i class="icon-lock"></i> 修改账户资料
            </div>
            <div class="widget-content">
                <div class="padd">

                    <form class="form-horizontal">
                        <!-- Registration form starts -->
                        <!-- Name -->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="name">姓名</label>
                            <div class="col-lg-9">
                                <input data-bind="value:name" type="text" class="form-control" id="name" placeholder="<?php echo $account->getName();?>">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg">&nbsp;</label>
                            <div class="col-lg-9">
                                <a href="<?php echo $this->url('account', array('action' => 'change-password')) ?>">
                                    修改密码
                                </a>
                            </div>
                        </div>
                        <!-- Accept box and button s-->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg">&nbsp;</label>
                            <div class="col-lg-9">
                                <button type="submit" data-bind="click:submit" class="btn btn-success">保存</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
            <div class="widget-foot">
            </div>
        </div>  
    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/account/edit-account']);});");
?>