<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
    <head>
        <?php //$this->headLink()->appendStylesheet('/styles/pagination.css');    ?>
        <?php echo $this->headTitle() ?>
        <meta http-equiv="Content-type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Stylesheets -->
        <link href="/mac/style/bootstrap.css" rel="stylesheet">
        <link rel="stylesheet" href="/mac/style/font-awesome.css">
        <link href="/mac/style/style.css" rel="stylesheet">
        <link href="/mac/style/bootstrap-responsive.css" rel="stylesheet">

        <!-- HTML5 Support for IE -->
        <!--[if lt IE 9]>
        <script src="/mac/js/html5shim.js"></script>
        <![endif]-->

        <!-- Favicon -->
        <link rel="shortcut icon" href="/mac/img/favicon/favicon.png">
    </head>

    <body>
        <!-- Form area -->
        <div class="admin-form">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <!-- Widget starts -->
                        <div class="widget worange">
                            <!-- Widget head -->
                            <div class="widget-head">
                                <i class="icon-lock"></i> 管理员登录 
                            </div>

                            <div class="widget-content">
                                <div class="padd">
                                    <!-- Login form -->
                                    <form class="form-horizontal">
                                        <!-- Email -->
                                        <div class="form-group">
                                            <label class="control-label col-lg-3" for="inputEmail">账号</label>
                                            <div class="col-lg-9">
                                                <input type="text" class="form-control" id="inputEmail" placeholder="请输入账号">
                                            </div>
                                        </div>
                                        <!-- Password -->
                                        <div class="form-group">
                                            <label class="control-label col-lg-3" for="inputPassword">密码</label>
                                            <div class="col-lg-9">
                                                <input type="password" class="form-control" id="inputPassword" placeholder="请输入密码">
                                            </div>
                                        </div>
                                        <!-- Remember me checkbox and sign in button -->
                                        <div class="form-group">
                                            <div class="col-lg-9 col-lg-offset-3">
                                                <div class="checkbox">
                                                    <label>
                                                        <input type="checkbox"> 记住密码
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-9 col-lg-offset-2">
                                            <button type="submit" class="btn btn-danger">登录</button>
                                            <button type="reset" class="btn btn-default">重置</button>
                                        </div>
                                        <br />
                                    </form>

                                </div>
                            </div>

                            <div class="widget-foot">
                                忘记密码? <a href="#">找回密码</a>
                            </div>
                        </div>  
                    </div>
                </div>
            </div> 
        </div>
        <!-- JS -->
        <script src="/mac/js/jquery.js"></script>
        <script src="/mac/js/bootstrap.js"></script>
    </body>
</html>