<!-- Form area -->
<div class="admin-form">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <!-- Widget starts -->
                <div class="widget worange">
                    <!-- Widget head -->
                    <div class="widget-head">
                        <i class="icon-lock"></i> 管理员登录
                    </div>

                    <div class="widget-content">
                        <div class="padd">
                            <!-- Login form -->
                            <form class="form-horizontal">
                                <!-- Email -->
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputEmail">账号</label>

                                    <div class="col-lg-9">
                                        <input type="text" data-bind="value:username" class="form-control" id="inputEmail" placeholder="请输入账号">
                                    </div>
                                </div>
                                <!-- Password -->
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputPassword">密码</label>

                                    <div class="col-lg-9">
                                        <input type="password" data-bind="value:password" class="form-control" id="inputPassword"
                                               placeholder="请输入密码">
                                    </div>
                                </div>
                                <!-- Remember me checkbox and sign in button -->
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputPassword">自动登录</label>
                                    <div class="col-lg-9">
                                        <div class="switch switch-small">
                                            <input type="checkbox" name='switch-checkbox' data-bind="value:rememberMe" />
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3" for="inputPassword">&nbsp;</label>
                                    <div class="col-lg-9">
                                        <button type="submit" data-bind="click:submit" class="btn btn-danger">登录</button>
                                        <button type="reset" class="btn btn-default">重置</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>

                    <div class="widget-foot">
<!--                        忘记密码? <a href="#">找回密码</a>-->&nbsp;
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->headScript()->appendScript("require(['main'],function(){require(['page/account/login']);});");?>