<div class="row">
    <div class="col-lg-6  col-lg-offset-3">
        <!-- Widget starts -->
        <div class="widget wred">
            <div class="widget-head">
                <i class="icon-lock"></i> 修改账户资料
            </div>
            <div class="widget-content">
                <div class="padd">

                    <form class="form-horizontal">
                        <!-- Registration form starts -->
                        <!-- Name -->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="name">姓名</label>
                            <div class="col-lg-9">
                                <input id="id" data-bind="value:id" data-value="<?php echo $this->escapeHtml($account->getId());?>" type="hidden"/>
                                <input data-bind="value:name" data-value="<?php echo $this->escapeHtml($account->getName());?>" type="text" class="form-control" id="name">
                            </div>
                        </div>
                        <!-- role-->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg" for="email">用户类型</label>
                            <div class="col-lg-9">
                                <select class="form-control" id="role" data-value="<?php echo $this->escapeHtml($account->getRole());?>" data-bind="value:role" >
                                    <?php foreach($roles as $role):?>
                                    <option value="<?php echo $role;?>"><?php echo $role;?></option>
                                    <?php endforeach;?>
                                </select>
<!--                                <input name="role" id="role" data-value="--><?php //echo $this->escapeHtml($account->getRole());?><!--" data-bind="value:role" type="hidden"/>-->
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg">&nbsp;</label>
                            <div class="col-lg-9">
                                <a href="<?php echo $this->url('account/wildcard', array('action' => 'reset-password','id'=>$account->getId())) ?>">
                                    重置密码
                                </a>
                            </div>
                        </div>
                        <!-- Accept box and button s-->
                        <div class="form-group">
                            <label class="control-label col-lg-3 visible-lg">&nbsp;</label>
                            <div class="col-lg-9">
                                <button type="submit" data-bind="click:submit" class="btn btn-success">保存</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
            <div class="widget-foot">
            </div>
        </div>  
    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/account/manage-account']);});");
?>