<div class="row">

    <div class="col-md-6">

        <div class="widget wred">
            <div class="widget-head">
                <div class="pull-left">系统设置</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>

            <div class="widget-content">
                <div class="padd">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">系统名称</label>
                            <div class="col-lg-8">
                                <input type="text" id="name" class="form-control" data-bind="value:name" data-value="" placeholder="输入系统名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-offset-4 col-lg-12">
                                <button type="submit" class="btn btn-success" data-bind="click:submitAndContinue">保存修改</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="widget-foot">
                <!-- Footer goes here -->
            </div>
        </div>  

    </div>

</div>