<!-- Form area -->
<div class="error-page">
    <div class="container">

        <div class="row">
            <div class="col-md-12">
                <!-- Widget starts -->
                <div class="widget">
                    <!-- Widget head -->
                    <div class="widget-head">
                        <i class="icon-question-sign"></i> 错误
                    </div>

                    <div class="widget-content">
                        <div class="padd error">

                            <h1>出错啦,心中一万只草泥马在奔腾~~~~(>_<)~~~~ </h1>
                            <br />
                            <p>系统错误,请联系系统管理员</p>
<!--                            <form class="form-inline">-->
<!--                                <div class="form-group">-->
<!--                                    <input type="text" value="" name="s" id="s" class="form-control"/>-->
<!--                                </div>-->
<!--                                <button type="submit" class="btn btn-default">Search</button>-->
<!--                            </form>-->

                            <br />
                            <div class="horizontal-links">
                                <a href="index">返回</a>
                            </div>

                        </div>
                        <div class="widget-foot">
                            <!-- Footer goes here -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>