<div class="row">
    <div class="col-md-6">
        <div class="widget wgreen">

            <div class="widget-head">
                <div class="pull-left">修改产品信息</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd">
                    <!-- Form starts.  -->
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">款号</label>
                            <div class="col-lg-8">
                                <input type="text" id="sku" class="form-control" data-bind="value:sku" data-value="<?php echo $product->getSku();?>" disabled>
                            </div>
                        </div>
<!--                        <div class="form-group">-->
<!--                            <label class="col-lg-4 control-label  visible-lg">图片</label>-->
<!--                            <div class="col-xs-8 col-lg-8">-->
<!--                                --><?php //echo $this->partial('imageuploader');?>
<!--                            </div>-->
<!--                        </div>-->
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">名称</label>
                            <div class="col-lg-8">
                                <input type="text" id="name" class="form-control" data-bind="value:name" data-value="<?php echo $product->getName();?>" placeholder="输入产品名称">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">进货价</label>
                            <div class="col-lg-8">
                                <input type="text" id="cost" class="form-control" data-bind="value:cost" data-value="<?php echo $product->getCost();?>" placeholder="输入产品进货价单价">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">库存</label>
                            <div class="col-lg-8">
                                <input type="text" id="stock" class="form-control" data-bind="value:stock" data-value="<?php echo $product->getStock();?>" placeholder="输入进货数量">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">零售价</label>
                            <div class="col-lg-8">
                                <input type="text" id="price" class="form-control" data-bind="value:price" data-value="<?php echo $product->getPrice();?>" placeholder="输入产品零售价(只作为参考价)">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-lg-4 control-label  visible-lg">描述</label>
                            <div class="col-lg-8">
                                <textarea class="form-control" id="description" rows="3" data-bind="value:description" data-value="<?php echo $product->getDescription();?>" placeholder="输入产品描述"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <!-- Buttons -->
                            <div class="col-lg-offset-4 col-lg-12">
                                <button type="submit" class="btn btn-success" data-bind="click:submitAndContinue">保存修改</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="widget-foot">
                <!-- Footer goes here -->
            </div>
        </div>

    </div>
</div>
<?php
$this->headScript()->appendScript("require(['main'],function(){require(['page/product/edit-product']);});");
?>