<div class="row">
    <div class="col-xs-12">
        <div class="pull-left">
            <div id="startTime" class="input-append" data-date-format="YYYY-MM-DD" style="width: 180px;">
                <input type="text" class="form-control dtpicker" placeholder="开始时间">
            <span class="add-on">
                <i data-time-icon="icon-time" data-date-icon="icon-calendar" class="btn btn-info btn-lg icon-calendar"></i>
            </span>
            </div>
        </div>
        <div class="pull-left">
            <div id="endTime" class="input-append" data-date-format="YYYY-MM-DD" style="width: 180px;">
                <input type="text" class="form-control dtpicker" placeholder="结束时间">
            <span class="add-on">
                <i data-time-icon="icon-time" data-date-icon="icon-calendar" class="btn btn-info btn-lg icon-calendar"></i>
            </span>
            </div>
        </div>
        <button type="submit" id="flushData" class="btn btn-success">刷新</button>
        <div class="clearfix"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <!-- Bar Chart -->
        <div class="widget">

            <div class="widget-head">
                <div class="pull-left">利润趋势</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="widget-content">
                <div class="padd">
                    <!-- Barchart. jQuery Flot plugin used. -->
                    <div id="bar-chart"></div>

                    <hr />
                    <div class="btn-group graphControls">
                        <input type="button" value="Lines" class="btn btn-default">
                        <input type="button" value="Lines with steps" class="btn btn-default">
                    </div>

                </div>
            </div>

        </div>
        <!-- Bar chart ends -->

    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <div class="widget" id="profitList">
            <div class="widget-head">
                <div class="pull-left">利润明细</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>  
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd statement">

                    <div class="row">

                        <div class="col-md-4">
                            <div class="well">
                                <h2 data-bind="text:priceSum()+'￥'"></h2>
                                <p>销售总额 (<span data-bind="text:startTime"></span> - <span data-bind="text:endTime"></span>)</p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="well">
                                <h2 data-bind="text:profitRate()+'%'"></h2>
                                <p>利润率 (<span data-bind="text:startTime"></span> - <span data-bind="text:endTime"></span>)</p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="well">
                                <h2 data-bind="text:profitSum()+'￥'"></h2>
                                <p>总利润 (<span data-bind="text:startTime"></span> - <span data-bind="text:endTime"></span>)</p>
                            </div>
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <hr>
                            <table class="table table-striped table-hover table-responsive table-bordered">
                                <thead>
                                    <tr>
                                        <th>日期</th>
                                        <th>当天利润(元)</th>
                                        <th>当天销售额(元)</th>
                                    </tr>
                                </thead>
                                <tbody data-bind="foreach:list">
                                    <tr>
                                        <td data-bind="text:date"></td>
                                        <td data-bind="text:priceAmount"></td>
                                        <td data-bind="text:profit"></td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>

                </div>
                <div class="widget-foot">
                </div>
            </div>
        </div>  

    </div>
</div>
<?php $this->headScript()->appendScript("require(['main'],function(){require(['page/statistics/profit']);});");?>
<?php $this->headLink()->appendStylesheet("/mac/style/bootstrap-datetimepicker.min.css");?>