<div class="row">
    <div class="col-xs-6">
        <div id="startTime" class="input-append">
            <input data-format="yyyy-MM-dd" type="text" class="form-control dtpicker" placeholder="开始时间">
            <span class="add-on">
                <i data-time-icon="icon-time" data-date-icon="icon-calendar" class="btn btn-info btn-lg icon-calendar"></i>
            </span>
        </div>
    </div>
    <div class="col-xs-6 col-md-pull-4">
        <div id="endTime" class="input-append">
            <input data-format="yyyy-MM-dd" type="text" class="form-control dtpicker" placeholder="结束时间">
            <span class="add-on">
                <i data-time-icon="icon-time" data-date-icon="icon-calendar" class="btn btn-info btn-lg icon-calendar"></i>
            </span>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <!-- Bar Chart -->
        <div class="widget">

            <div class="widget-head">
                <div class="pull-left">利润趋势</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="widget-content">
                <div class="padd">
                    <!-- Barchart. jQuery Flot plugin used. -->
                    <div id="bar-chart"></div>

                    <hr />

                    <!--Bar chart stuffs -->
                    <div class="btn-group stackControls">
                        <input type="button" value="With stacking" class="btn btn-default">
                        <input type="button" value="Without stacking" class="btn btn-default">
                    </div>

                    <div class="btn-group graphControls">

                        <input type="button" value="Bars" class="btn btn-default">
                        <input type="button" value="Lines" class="btn btn-default">
                        <input type="button" value="Lines with steps" class="btn btn-default">
                    </div>

                </div>
            </div>

        </div>
        <!-- Bar chart ends -->

    </div>
</div>
<div class="row">
    <div class="col-md-12">

        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">利润明细</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>  
                <div class="clearfix"></div>
            </div>
            <div class="widget-content">
                <div class="padd statement">

                    <div class="row">

                        <div class="col-md-4">
                            <div class="well">
                                <h2>$8488</h2>
                                <p>销售总额 (23/23/2023 - 23/43/2021)</p>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="well">
                                <h2>34%</h2>
                                <p>利润率 (23/23/2023 - 23/43/2021)</p>                        
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="well">
                                <h2>$23232</h2>
                                <p>总利润 (23/23/2023 - 23/43/2021)</p>
                            </div>
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-md-12">
                            <hr>
                            <table class="table table-striped table-hover table-responsive table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Earnings</th>
                                        <th>Order ID</th>
                                        <th>Buyer</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Sony Xperia Pro X1242</td>
                                        <td>$25</td>
                                        <td>534343</td>
                                        <td>Ravi Kumar</td>
                                        <td>3 Days ago</td>
                                    </tr>     
                                    <tr>
                                        <td>2</td>
                                        <td>Apple iPhone 6G - Black</td>
                                        <td>$15</td>
                                        <td>565445</td>
                                        <td>Babu Raj</td>
                                        <td>6 Days ago</td>
                                    </tr>                                                                        <tr>
                                        <td>3</td>
                                        <td>Samsung Galaxy Metro</td>
                                        <td>$35</td>
                                        <td>976876</td>
                                        <td>Ashok</td>
                                        <td>8 Days ago</td>
                                    </tr> 
                                    <tr>
                                        <td>4</td>
                                        <td>Nokia Lumina Asha</td>
                                        <td>$22</td>
                                        <td>232454</td>
                                        <td>Raja Ram</td>
                                        <td>10 Days ago</td>
                                    </tr> 
                                    <tr>
                                        <td>5</td>
                                        <td>Motorola Razr 5304</td>
                                        <td>$18</td>
                                        <td>787876</td>
                                        <td>Kumerasa</td>
                                        <td>12 Days ago</td>
                                    </tr> 
                                    <tr>
                                        <td>6</td>
                                        <td>Micromox Canvas Small</td>
                                        <td>$30</td>
                                        <td>656543</td>
                                        <td>Sagunai</td>
                                        <td>15 Days ago</td>
                                    </tr>                                                                                                                     
                                    <tr>  
                                        <td></td>
                                        <td><strong>Total</strong></td>
                                        <td><strong>$485</strong></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>

                    </div>

                </div>
                <div class="widget-foot">
                </div>
            </div>
        </div>  

    </div>
</div>
<?php $this->headScript()->appendScript("require(['main'],function(){require(['page/statistics/profit']);});");?>
<?php $this->headLink()->appendStylesheet("/mac/style/bootstrap-datetimepicker.min.css");?>