<?php
/**
 * @var $this Zend\View\Renderer\PhpRenderer
 */
?>
<?php echo $this->doctype(); ?>

<html lang="zh">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('XSale ' . $this->translate($this->about['softwareName']))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    $this->headLink()->headLink(array('rel' => 'favicon',
            'href' => '/default/img/favicon.ico'),
        'PREPEND');
    ?>

    <link href="/mac/style/bootstrap.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <!-- Font awesome icon -->
    <link rel="stylesheet" href="/mac/style/font-awesome.css">

    <link rel="stylesheet" href="/mac/style/jquery-ui.css">
    <!-- Calendar -->
    <link rel="stylesheet" href="/mac/style/fullcalendar.css">
    <!-- prettyPhoto -->
    <link rel="stylesheet" href="/mac/style/prettyPhoto.css">
    <!-- Star rating -->
    <link rel="stylesheet" href="/mac/style/rateit.css">
    <!-- CLEditor -->
    <link rel="stylesheet" href="/mac/style/jquery.cleditor.css">
    <!-- Uniform -->
    <link rel="stylesheet" href="/mac/style/uniform.default.css">
    <!-- Bootstrap toggle -->
    <link rel="stylesheet" href="/mac/style/bootstrap-switch.css">
    <!-- Main stylesheet -->
    <link href="/mac/style/style.css" rel="stylesheet">
    <!-- Widgets stylesheet -->
    <link href="/mac/style/widgets.css" rel="stylesheet">

    <link href="/default/style/css/default.css" rel="stylesheet">

    <link href="/default/style/css/pace-theme-minimal.css" rel="stylesheet">

    <script data-main="/default/js/main" src="/default/js/require.js"></script>

    <script type="text/javascript">
        require(['lib/json2'], function () {
            xsaleConfig = JSON.parse('<?php echo json_encode($this->xsaleConfig);?>');
        });
    </script>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

</head>
<body>
<div class="navbar navbar-fixed-top bs-docs-nav" role="banner">

    <div class="conjtainer">
        <!-- Menu button for smallar screens -->
        <div class="navbar-header">
            <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse"
                    data-target=".bs-navbar-collapse">
                <span>菜单</span>
            </button>
            <!-- Site name for smallar screens -->
            <a href="index.html" class="navbar-brand hidden-lg"><?php echo $this->translate($this->about['softwareName']); ?></a>
        </div>


        <!-- Navigation starts -->
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">

            <ul class="nav navbar-nav">

                <!-- Upload to server link. Class "dropdown-big" creates big dropdown -->
                <!-- Sync to server link -->
                <li>
                    <a href="<?php echo $this->url('home') ?>"><span class="label label-primary"><i
                                class="icon-home"></i></span> 回到主页</a>
                </li>
                <li>
                    <a href="/saleRecord/check-out"><span class="label label-success"><i class="icon-money"></i></span>
                        结账页</a>
                </li>

            </ul>

            <!-- Links -->
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown pull-right">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <i class="icon-user"></i>
                        <?php
                        if ($user = $this->identity()) {
                            echo $this->escapeHtml($user->getName());
                        } else {
                            echo 'Not logged in';
                        }
                        ?>
                        <b class="caret"></b>
                    </a>

                    <!-- Dropdown menu -->
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('account', array('action' => 'edit-account')) ?>"><i
                                    class="icon-user"></i> 资料</a></li>
                        <li><a href="<?php echo $this->url('setting', array('action' => 'system')) ?>"><i
                                    class="icon-cogs"></i> 设置</a></li>
                        <li><a href="<?php echo $this->url('logout'); ?>"><i class="icon-off"></i> 退出</a></li>
                    </ul>
                </li>

            </ul>
        </nav>

    </div>
</div>


<!-- Header starts -->
<header>
    <div class="container">
        <div class="row">

            <!-- Logo section -->
            <div class="col-md-4">
                <!-- Logo. -->
                <div class="logo">
                    <h1><a class="title-font" href="#"><?php echo $this->translate($this->about['softwareName']); ?><span
                                class="bold"></span></a></h1>

                    <p class="meta"><?php echo $this->about['version'] ?></p>
                </div>
                <!-- Logo ends -->
            </div>

            <!-- Button section -->
            <div class="col-md-4">

            </div>

            <!-- Data section -->

            <div class="col-md-8 pull-right">
                <div class="header-data pull-right">

                    <!-- Traffic data -->
                    <div class="hdata">
                        <div class="mcol-left">
                            <!-- Icon with red background -->
                            <i class="icon-signal bred"></i>
                        </div>
                        <div class="mcol-right">
                            <!-- Number of visitors -->
                            <p><a href="#"><?php echo $this->quantityOfSale ?></a> <em>销售量</em></p>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <!-- Members data -->
                    <div class="hdata">
                        <div class="mcol-left">
                            <!-- Icon with blue background -->
                            <i class="icon-user bblue"></i>
                        </div>
                        <div class="mcol-right">
                            <!-- Number of visitors -->
                            <p><a href="#"><?php echo $this->vipCount; ?></a> <em>VIP</em></p>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                    <!-- revenue data -->
                    <div class="hdata">
                        <div class="mcol-left">
                            <!-- Icon with green background -->
                            <i class="icon-money bgreen"></i>
                        </div>
                        <div class="mcol-right">
                            <!-- Number of visitors -->
                            <p><a href="#"><?php echo $this->saleroom ?></a><em>销售额</em></p>
                        </div>
                        <div class="clearfix"></div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</header>

<!-- Header ends -->

<!-- Main content starts -->
<div class="content">

    <!-- Sidebar -->
    <div class="sidebar" id="sidebarContent">
        <div class="sidebar-dropdown"><a href="#">导航</a></div>
        <!--- Sidebar navigation -->
        <!-- If the main navigation has sub navigation, then add the class "has_sub" to "li" of main navigation. -->
        <ul id="nav">
            <!-- Main menu with font awesome icon -->
            <li><a href="<?php echo $this->url('home') ?>" class="open"><i class="icon-home"></i> 首页</a>
            </li>
            <li class="has_sub"><a href="<?php echo $this->url('stock-record', array('action' => 'index')) ?>"><i
                        class="icon-list-alt"></i> 进货 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'stock-record') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'index' && $this->controller == 'stock-record') echo 'class="active"' ?>
                            href="<?php echo $this->url('stock-record', array('action' => 'index')) ?>">所有进货记录</a></li>
                    <li>
                        <a <?php if ($this->action == 'create-record' && $this->controller == 'stock-record') echo 'class="active"' ?>
                            href="<?php echo $this->url('stock-record', array('action' => 'create-record')) ?>">添加进货记录</a>
                    </li>
                </ul>
            </li>
            <li class="has_sub"><a href="<?php echo $this->url('sale-record', array('action' => 'index')) ?>"><i
                        class="icon-list-alt"></i> 出货 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'sale-record') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'index' && $this->controller == 'sale-record') echo 'class="active"' ?>
                            href="<?php echo $this->url('sale-record', array('action' => 'index')) ?>">所有销售记录</a></li>
                    <li>
                        <a <?php if ($this->action == 'create-record' && $this->controller == 'sale-record') echo 'class="active"' ?>
                            href="<?php echo $this->url('sale-record', array('action' => 'create-record')) ?>">添加销售记录</a>
                    </li>
                </ul>
            </li>
            <li class="has_sub"><a href="<?php echo $this->url('product', array('action' => 'index')) ?>"><i
                        class="icon-list-alt"></i> 产品 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'product') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'index' && $this->controller == 'product') echo 'class="active"' ?>
                            href="<?php echo $this->url('product', array('action' => 'index')) ?>">所有产品</a></li>
                </ul>
            </li>
            <li class="has_sub"><a href="<?php echo $this->url('customer', array('action' => 'index')) ?>"><i
                        class="icon-list-alt"></i> 客户 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'customer') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'index' && $this->controller == 'customer') echo 'class="active"' ?>
                            href="<?php echo $this->url('customer', array('action' => 'index')) ?>">所有客户</a></li>
                    <li>
                        <a <?php if ($this->action == 'create-customer' && $this->controller == 'customer') echo 'class="active"' ?>
                            href="<?php echo $this->url('customer', array('action' => 'create-customer')) ?>">添加客户</a>
                    </li>
                </ul>
            </li>
            <li class="has_sub"><a href="<?php echo $this->url('statistics', array('action' => 'profit')) ?>"><i
                        class="icon-list-alt"></i> 统计 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'statistics') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'profit' && $this->controller == 'statistics') echo 'class="active"' ?>
                            href="<?php echo $this->url('statistics', array('action' => 'profit')) ?>">总体统计</a></li>
                    <!--                        <li><a -->
                    <?php //if($this->action=='sold'&&$this->controller=='statistics')echo 'class="active"'?><!-- href="-->
                    <?php //echo $this->url('statistics',array('action'=>'sold'))?><!--">产品统计</a></li>-->
                    <!--                        <li><a -->
                    <?php //if($this->action=='hot-sell'&&$this->controller=='statistics')echo 'class="active"'?><!-- href="-->
                    <?php //echo $this->url('statistics',array('action'=>'hot-sell'))?><!--">热销产品</a></li>-->
                </ul>
            </li>
            <?php
            $acl = \Application\Lib\Acl\Acl::getInstance();
            $user = $this->identity();
            ?>
            <?php if (isset($user) && $acl->isAllowed($this->identity()->getRole(), 'account/index')): ?>
                <li class="has_sub"><a href="<?php echo $this->url('account', array('action' => 'index')) ?>"><i
                            class="icon-list-alt"></i> 账户 <span class="pull-right"><i
                                class="icon-chevron-right"></i></span></a>
                    <ul <?php if ($this->controller == 'account') echo 'style="display:block;"' ?>>
                        <li>
                            <a <?php if ($this->action == 'index' && $this->controller == 'account') echo 'class="active"' ?>
                                href="<?php echo $this->url('account', array('action' => 'index')) ?>">所有账户</a></li>
                        <li>
                            <a <?php if ($this->action == 'create-account' && $this->controller == 'account') echo 'class="active"' ?>
                                href="<?php echo $this->url('account', array('action' => 'create-account')) ?>">添加账户</a>
                        </li>
                    </ul>
                </li>
            <?php endif; ?>
            <li class="has_sub"><a href="<?php echo $this->url('setting', array('action' => 'system')) ?>"><i
                        class="icon-list-alt"></i> 设置 <span class="pull-right"><i class="icon-chevron-right"></i></span></a>
                <ul <?php if ($this->controller == 'setting') echo 'style="display:block;"' ?>>
                    <li>
                        <a <?php if ($this->action == 'system' && $this->controller == 'setting') echo 'class="active"' ?>
                            href="<?php echo $this->url('setting', array('action' => 'system')) ?>">系统设置</a></li>
                    <!--                        <li><a -->
                    <?php //if($this->action=='others'&&$this->controller=='setting')echo 'class="active"'?><!-- href="-->
                    <?php //echo $this->url('setting',array('action'=>'others'))?><!--">其他设置</a></li>-->
                </ul>
            </li>
        </ul>
    </div>

    <!-- Sidebar ends -->

    <!-- Main bar -->
    <div class="mainbar">
        <!-- Matter -->

        <div class="matter">
            <div class="container">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>

        <!-- Matter ends -->

    </div>

    <!-- Mainbar ends -->
    <div class="clearfix"></div>

</div>
<!-- Content ends -->

<!-- Footer starts -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Copyright info -->
                <p class="copy">&copy; <?php echo date('Y') ?> <?php echo $this->about['author'] ?>. All rights
                    reserved. | <a href="#"><?php echo $this->translate($this->about['softwareName']); ?>
                        by <?php echo $this->about['author'] ?></a></p>
            </div>
        </div>
    </div>
</footer>

<!-- Footer ends -->

<!-- Scroll to top -->
<span class="totop"><a href="#"><i class="icon-chevron-up"></i></a></span>

<?php echo $this->inlineScript(); ?>
</body>
</html>
