<?php $this->headLink()->appendStylesheet('/default/style/css/jquery.fileupload.css');?>
<span class="btn btn-default fileinput-button">
    <i class="icon-plus"></i>
    <span>添加图片</span>
    <!-- The file input field used as target for the file upload widget -->
    <!-- TODO 上传按钮点击范围-->
    <input id="fileupload" data-file-upload type="file" name="files[]" multiple>
</span>
<!-- The container for the uploaded files -->
<div id="files" class="files"></div>