<!-- Dashboard Graph starts -->
<?php $conf = $this->layout()->xsaleConfig;?>
<div class="row">
    <div class="col-md-8">
        <!-- Bar Chart -->
        <div class="widget">

            <div class="widget-head">
                <div class="pull-left">利润趋势</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>


            <div class="widget-content">
                <div class="padd">
                    <!-- Barchart. jQuery Flot plugin used. -->
                    <div id="bar-chart"></div>

                    <hr />
                    <div class="btn-group graphControls">
                        <input type="button" value="Lines" class="btn btn-default">
                        <input type="button" value="Lines with steps" class="btn btn-default">
                    </div>

                </div>
            </div>

        </div>
        <!-- Bar chart ends -->
    </div>

    <div class="col-md-4">
        <div class="widget">
                    <div class="widget-head">
                        <div class="pull-left">过去30天销量TOP<?php echo is_array($topSale)?count($topSale):''?></div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                            <a href="#" class="wclose"><i class="icon-remove"></i></a>
                        </div>  
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content medias">

                        <table id="record-list" class="table table-striped table-bordered table-hover">
                            <tbody>
                            <?php foreach($topSale as $sale):?>
                                <tr>
                                    <td><img src="<?php echo $conf['thumbnailPath'].($sale['picture']?$sale['picture']:$conf['defaultImage']);?>" alt=""></td>
                                    <td>
                                        <a href="<?php echo $this->url('product/wildcard',array('action'=>'edit-product','id'=>$sale['product_id']));?>">
                                            <?php echo $sale['sku'];?>
                                        </a>
                                        /<?php echo $sale['name'];?>
                                    </td>
                                    <td><?php echo $sale['sold'];?>件</td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
    </div>
</div>
<!-- Dashboard graph ends -->

<!-- Chats, File upload and Recent Comments -->
<div class="row">

    <div class="col-md-8">
        <!-- Widget -->
        <div class="row">
            <div class="col-md-12">
                <div class="widget">
                    <div class="widget-head">
                        <div class="pull-left">最近销售记录</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                            <a href="#" class="wclose"><i class="icon-remove"></i></a>
                        </div>  
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content medias">

                        <table id="record-list" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>图片</th>
                                    <th>订单号</th>
                                    <th>款号/名称</th>
                                    <th>总数量</th>
                                    <th>总价</th>
                                    <th>结账时间</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($recentOrder as $order):?>
                                <tr>
                                    <td>
                                        <img src="<?php echo $conf['thumbnailPath'].($order['picture']?$order['picture']:$conf['defaultImage']);?>" alt="">
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('sale-record/wildcard',array('action'=>'edit-record','id'=>$order['order_id']))?>"><?php echo $order['order_id'];?></a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('product/wildcard',array('action'=>'edit-product','id'=>$order['product_id']))?>">
                                            <?php echo $order['sku'];?>
                                        </a>
                                        /<?php echo $order['name'];?>
                                    </td>
                                    <td><?php echo $order['quantity'];?></td>
                                    <td><?php echo $order['price']*$order['quantity'];?></td>
                                    <?php $orderTime = new DateTime($order['order_time']);?>
                                    <td><?php echo $orderTime->format('Y-m-d');?></td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="widget">
                    <div class="widget-head">
                        <div class="pull-left">最近进货记录</div>
                        <div class="widget-icons pull-right">
                            <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
                            <a href="#" class="wclose"><i class="icon-remove"></i></a>
                        </div>  
                        <div class="clearfix"></div>
                    </div>
                    <div class="widget-content medias">

                        <table id="record-list" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>图片</th>
                                    <th>进货单号</th>
                                    <th>款号/名称</th>
                                    <th>总数量</th>
                                    <th>总价</th>
                                    <th>进货时间</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php foreach($recentStock as $stock):?>
                                <tr>
                                    <td>
                                        <img src="<?php echo $conf['thumbnailPath'].($stock['picture']?$stock['picture']:$conf['defaultImage']);?>" alt="">
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('stock-record/wildcard',array('action'=>'edit-record','id'=>$stock['stock_record_id']))?>"><?php echo $stock['stock_record_id'];?></a>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('product/wildcard',array('action'=>'edit-product','id'=>$stock['product_id']))?>">
                                            <?php echo $stock['sku'];?>
                                        </a>
                                        /<?php echo $stock['name'];?>
                                    </td>
                                    <td><?php echo $stock['quantity'];?></td>
                                    <td><?php echo $stock['price']*$stock['quantity'];?></td>
                                    <?php $stockTime = new DateTime($stock['stock_time']);?>
                                    <td><?php echo $stockTime->format('Y-m-d');?></td>
                                </tr>
                            <?php endforeach;?>
                            </tbody>
                        </table>
                    </div>
                </div> 
            </div>
        </div>

    </div>

    <div class="col-md-4">
        <!-- Widget -->
        <div class="widget">
            <div class="widget-head">
                <div class="pull-left">库存警告</div>
                <div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="wclose"><i class="icon-remove"></i></a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content medias">

                <table id="record-list" class="table table-striped table-bordered table-hover">
                    <tbody>
                    <?php foreach($stockWarning as $product):?>
                        <tr>
                            <td><img src="<?php echo $conf['thumbnailPath'].($product->getPicture()?$product->getPicture():$conf['defaultImage']);?>" alt=""></td>
                            <td>
                                <a href="<?php echo $this->url('product/wildcard',array('action'=>'edit-product','id'=>$product->getId()));?>">
                                    <?php echo $product->getSku();?>
                                </a>
                                /<?php echo $product->getName();?>
                            </td>
                            <td style="color: #b94a48">剩余<?php echo $product->getStock();?>件</td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>

    </div>
</div>
<?php $this->headScript()->appendScript("require(['main'],function(){require(['page/index/index']);});");?>
